version: '3.2'
services:
  test:
    container_name: erbloom.test
    build:
      context: imgs/base
      args:
        UID: "${UID:?Please export UID}"
        GID: "${GID:?Please export GID}"
    user: "${UID:?Please export UID}:${GID:?Please export GID}"
    volumes:
      - "./:/project"
    tmpfs:
      - /run
      - /tmp
